### ISSUE TITLE
Certificate Expired, Please Update

### ISSUE THREAD

**Issue by tzafarpk** [chris-marsh/fastIPvanish#3] opened 2017-01-11 09:21 UTC
Ipvanish certificate in your code has expired and users are unable to connect with vpn so please update your certificate file (ca.ipvanish.com.crt)

**Comment by chris-marsh** [comment] 2017-01-11 18:04
Thanks for the heads up. The certificate has now been updated.

I plan to have the script automatically update the certificate in future versions, ~~but the issue is fixed for now~~. However, it appears updating the certificate from https://www.ipvanish.com/software/configs has not resolved the problem.

[Update]
After some more testing we seem to be all good now :)

I'd be grateful if you could confirm and we can close this issue.

**Comment by tzafarpk** [comment] 2017-01-12 10:30
Thanks for the update, My OS is Kali Linux and i didn't seem any other issue with it except certificate update error and script working fine for me. Good to hear you are going to add new feature in the script and looking forward to it.

**Closed as completed** 2017-01-12 12:07 UTC
